/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './translation.module';
class TranslationModuleInjector extends import0.ɵNgModuleInjector<import1.TranslationModule> {
  _TranslationModule_0:import1.TranslationModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.TranslationModule {
    this._TranslationModule_0 = new import1.TranslationModule();
    return this._TranslationModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.TranslationModule)) { return this._TranslationModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const TranslationModuleNgFactory:import0.NgModuleFactory<import1.TranslationModule> = new import0.NgModuleFactory<any>(TranslationModuleInjector,import1.TranslationModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2RhdmUvRGV2ZWxvcG1lbnQvR3l1bnUvbmctdHJhbnNsYXRlL3NyYy90cmFuc2xhdGlvbi5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZGF2ZS9EZXZlbG9wbWVudC9HeXVudS9uZy10cmFuc2xhdGUvc3JjL3RyYW5zbGF0aW9uLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
